plugins {
    id "immediatelyfast.platform-conventions"
}

architectury {
    fabric()
}

configurations {
    developmentFabric.extendsFrom(common)
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation(include("net.lenni0451:Reflect:${project.reflect_version}"))
    includeInJar(project(path: ":common", configuration: "transformProductionFabric")) {
        transitive = false
    }
}

processResources {
    inputs.property("version", project.version)

    def projectVersion = project.version
    filesMatching("fabric.mod.json") {
        expand("version": projectVersion)
    }
}
