plugins {
    id "immediatelyfast.platform-conventions"
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    include "net.lenni0451:Reflect:${project.reflect_version}"
}

processResources {
    inputs.property("version", project.version)

    def projectVersion = project.version
    filesMatching("fabric.mod.json") {
        expand("version": projectVersion)
    }
}
