version: 2
registries:
  maven-central:
    type: "maven-repository"
    url: "https://repo.maven.apache.org/maven2/"
  architectury-maven:
    type: "maven-repository"
    url: "https://maven.architectury.dev/"
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - "maven-central"
      - "architectury-maven"
  - package-ecosystem: "gradle"
    directory: "/common"
    schedule:
      interval: "daily"
    registries:
      - "maven-central"
      - "architectury-maven"
  - package-ecosystem: "gradle"
    directory: "/fabric"
    schedule:
      interval: "daily"
    registries:
      - "maven-central"
      - "architectury-maven"
  - package-ecosystem: "gradle"
    directory: "/neoforge"
    schedule:
      interval: "daily"
    registries:
      - "maven-central"
      - "architectury-maven"
  - package-ecosystem: "gradle"
    directory: "/forge"
    schedule:
      interval: "daily"
    registries:
      - "maven-central"
      - "architectury-maven"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
