plugins {
    id "java-library"
    id "base.base-conventions"
    id "dev.architectury.loom-no-remap"
    id "me.modmuss50.mod-publish-plugin"
}

loom {
    mixin {
        useLegacyMixinAp = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
}

publishMods {
    type = STABLE
    displayName = rootProject.name + ' ' + project.version.substring(0, project.version.lastIndexOf('+'))
    changelog = file("../CHANGELOG.md").text
    dryRun = project.maven_version.contains("SNAPSHOT")

    github {
        accessToken = providers.gradleProperty("github.immediatelyfast_publishing_token")
        repository = "RaphiMC/ImmediatelyFast"
        changelog = "**Changelog**\n" + file("../CHANGELOG.md").text
        commitish = project.git_branch
        tagName = 'v' + project.version.substring(0, project.version.lastIndexOf('+'))
        allowEmptyFiles = true
    }
}
