plugins {
    id "base.exclude-run-folder"
    id "immediatelyfast.base-conventions"
    id "immediatelyfast.publishing-conventions"
    id "base.include-in-jar-configuration"
}

base {
    archivesName = project.jar_name
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    mods {
        "immediatelyfast" {
            sourceSet(project(":common").sourceSets.main)
            sourceSet(project.sourceSets.main)
        }
    }
    runs.configureEach {
        generateRunConfig = true
    }
}

dependencies {
    includeInJar(project(path: ":common", configuration: "namedElements")) {
        transitive = false
    }
}

jar {
    exclude("assets/immediatelyfast/icon-full.png")
}
