plugins {
    id "me.modmuss50.mod-publish-plugin"
}

publishMods {
    file = jar.archiveFile
    version = project.version + '-' + loom.platform.get().id()
    modLoaders.add(loom.platform.get().id())
    if (project.name == "fabric") {
        modLoaders.add("quilt")
    }

    curseforge {
        accessToken = providers.gradleProperty("curseforge.publishing_token")
        projectId = "686911"
        minecraftVersionList(project.supported_minecraft_versions)
        javaVersions.add(JavaVersion.toVersion(java.toolchain.languageVersion.get().asInt()))
        client = true
        server = false
    }
    modrinth {
        accessToken = providers.gradleProperty("modrinth.publishing_token")
        projectId = "5ZwdcRci"
        minecraftVersionList(project.supported_minecraft_versions)
    }
    github {
        parent project(":common").tasks.named("publishGithub")
    }
}
