plugins {
    id "base.exclude-run-folder"
    id "immediatelyfast.base-conventions"
    id "immediatelyfast.publishing-conventions"
    id "base.include-in-jar-configuration"
}

base {
    archivesName = project.jar_name
}

architectury {
    platformSetupLoomIde()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common

    compileClasspath.extendsFrom(common)
    runtimeClasspath.extendsFrom(common)
}

dependencies {
    common(project(":common")) {
        transitive = false
    }
}

jar {
    exclude("assets/immediatelyfast/icon-full.png")
}
