org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4G

git_branch=1.21.11
minecraft_version=1.21.11
supported_minecraft_versions=1.21.11
parchment_mappings=1.21.11:2025.12.20
fabric_loader_version=0.18.6
neoforge_version=21.11.42
reflect_version=1.6.2

java_version=21
maven_group=net.raphimc
maven_name=ImmediatelyFast
maven_version=1.14.4-SNAPSHOT+1.21.11
