org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4G

git_branch=1.21
minecraft_version=1.21.1
supported_minecraft_versions=1.21,1.21.1
yarn_mappings=1.21.1+build.3
fabric_loader_version=0.16.14
forge_version=1.21.1-52.1.8
neoforge_version=21.1.216
mixin_extras_version=0.4.1
reflect_version=1.6.1+curseforge

java_version=21
maven_group=net.raphimc
maven_name=ImmediatelyFast
maven_version=1.6.10-SNAPSHOT+1.21.1
