org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4G

git_branch=26.2
minecraft_version=26.2
supported_minecraft_versions=26.2
fabric_loader_version=0.19.3
neoforge_version=26.2.0.1-beta

java_version=25
maven_group=net.raphimc
maven_name=ImmediatelyFast
maven_version=1.16.1-SNAPSHOT+26.2
