plugins {
    id "immediatelyfast.base-conventions"
}

architectury {
    common("fabric")
    common("neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/immediatelyfast.classtweaker")
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"))
    implementation("net.lenni0451:Reflect:${project.reflect_version}")
}
