plugins {
    id "immediatelyfast.platform-conventions"
}

loom {
    neoForge {
        convertAccessWideners(tasks.named("remapJar"), loom.accessWidenerPath.get().getAsFile().name)
    }
}

repositories {
    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"
    include "net.lenni0451:Reflect:${project.reflect_version}"
}

processResources {
    inputs.property("version", project.version)

    def projectVersion = project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand("version": projectVersion)
    }
}

jar {
    from("../common/src/main/resources/assets/immediatelyfast/icon.png") {
        rename { "immediatelyfast-icon.png" }
    }
}
