plugins {
    id "immediatelyfast.platform-conventions"
}

architectury {
    neoForge()
}

configurations {
    developmentNeoForge.extendsFrom(common)
}

repositories {
    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    neoForge("net.neoforged:neoforge:${project.neoforge_version}")
    forgeRuntimeLibrary(implementation(include("net.lenni0451:Reflect:${project.reflect_version}")))
    includeInJar(project(path: ":common", configuration: "transformProductionNeoForge")) {
        transitive = false
    }
}

/*remapJar {
    atAccessWideners.add(loom.accessWidenerPath.get().asFile.name)
}*/

processResources {
    inputs.property("version", project.version)

    def projectVersion = project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand("version": projectVersion)
    }
}
